language: java

services:
  - docker

before_install:
  - docker pull datastax/dse-server:5.1.6
  - docker run -e DS_LICENSE=accept -e LISTEN_ADDRESS=127.0.0.1 -e START_RPC=true --name dse -d -p 8182:8182 -p 9042:9042 datastax/dse-server:5.1.6 -g
  - docker ps -a

script:
  - gradle check
  - gradle codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)